image: maven:3-jdk-11

variables:
  MAVEN_CLI_OPTS: "--errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mvn clean verify jacoco:report
    - cat lemaf4j-vo/target/site/jacoco/index.html
    - mkdir public
    - mv lemaf4j-vo/target/site/jacoco/index.html public
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS verify
  only:
    - master